common_properties: &common_properties
  docker:
    - image: circleci/node:9-browsers
  working_directory: ~/trollepierre/recontact_travel_blog

version: 2
jobs:
  checkout_code:
    <<: *common_properties
    steps:
      - checkout
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - save_cache:
          key: v1-code-{{ checksum ".circle-cache-key" }}
          paths:
            - ~/trollepierre/recontact_travel_blog

  install_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v1-front-dependencies-{{ checksum "client/yarn.lock" }}
      - run:
          name: Install front
          command: yarn install:client
      - save_cache:
          key: v1-front-dependencies-{{ checksum "client/yarn.lock" }}
          paths:
            - ./client/node_modules

  install_back:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v1-back-dependencies-{{ checksum "server/yarn.lock" }}
      - run:
          name: Install back
          command: yarn install:server
      - save_cache:
          key: v1-back-dependencies-{{ checksum "server/yarn.lock" }}
          paths:
            - ./server/node_modules

  test_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v1-front-dependencies-{{ checksum "client/yarn.lock" }}
      - run:
          name: Lint front
          command: yarn lint:client
      - run:
          name: Test front
          command: yarn test:client
      - store_test_results:
          path: /tmp/circleci-test-results/front

  test_back:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v1-back-dependencies-{{ checksum "server/yarn.lock" }}
      - run:
          name: Lint back
          command: yarn lint:server
      - run:
          name: Test back
          command: yarn test:server
      - store_test_results:
          path: /tmp/circleci-test-results/back

  build_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v1-front-dependencies-{{ checksum "client/yarn.lock" }}
      - run: yarn build

  deploy_branch:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy branch to Heroku branch
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/recontact-branch.git $CIRCLE_BRANCH:master --force

  validate_accessibility_html5v:
    <<: *common_properties
    steps:
      - run: yarn add html5-validator
      - run: ./node_modules/.bin/html5v https://recontact-branch.herokuapp.com/

  validate_accessibility_pa11y:
    <<: *common_properties
    steps:
      - run: yarn add pa11y
      - run: ./node_modules/.bin/pa11y -T 10 https://recontact-branch.herokuapp.com/

  deploy_staging:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy dev to Heroku staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/recontact-test.git dev:master

  deploy_master:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v1-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/recontact.git master

workflows:
  version: 2
  recontact-workflow:
    jobs:
      - checkout_code
      - install_front:
          requires:
            - checkout_code
      - install_back:
          requires:
            - checkout_code
      - test_front:
          requires:
            - install_front
      - test_back:
          requires:
            - install_back
      - build_front:
          requires:
            - install_front
      - deploy_branch:
          requires:
            - test_front
            - test_back
            - build_front
          filters:
            branches:
              ignore:
                - dev
                - master
      - validate_accessibility_html5v:
          requires:
            - deploy_branch
      - validate_accessibility_pa11y:
          requires:
            - deploy_branch
      - deploy_staging:
          requires:
            - test_front
            - test_back
            - build_front
          filters:
            branches:
              only: dev
      - deploy_master:
          requires:
            - test_front
            - test_back
            - build_front
          filters:
            branches:
              only: master

