common_properties: &common_properties
  docker:
    - image: circleci/node:12.16.1-browsers
  working_directory: ~/trollepierre/recontact_travel_blog

version: 2
jobs:
  checkout_code:
    <<: *common_properties
    steps:
      - checkout
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - save_cache:
          key: v2-code-{{ checksum ".circle-cache-key" }}
          paths:
            - ~/trollepierre/recontact_travel_blog

  install_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-dependencies-{{ checksum "front/yarn.lock" }}
      - run:
          name: Install front
          command: yarn install:front --frozen-lockfile
      - save_cache:
          key: v2-front-dependencies-{{ checksum "front/yarn.lock" }}
          paths:
            - ./front/node_modules

  install_back:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-back-dependencies-{{ checksum "back/yarn.lock" }}
      - run:
          name: Install back
          command: yarn install:back --frozen-lockfile
      - save_cache:
          key: v2-back-dependencies-{{ checksum "back/yarn.lock" }}
          paths:
            - ./back/node_modules

  test_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-dependencies-{{ checksum "front/yarn.lock" }}
      - run:
          name: Lint front
          command: yarn lint:front
      - run:
          name: Test front
          command: yarn test:front:ci
      - store_test_results:
          path: /tmp/circleci-test-results/front

  test_back:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-back-dependencies-{{ checksum "back/yarn.lock" }}
      - run:
          name: Lint back
          command: yarn lint:back
      - run:
          name: Test back
          command: yarn test:back
      - store_test_results:
          path: /tmp/circleci-test-results/back

  build_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-dependencies-{{ checksum "front/yarn.lock" }}
      - run: yarn build:front
      - save_cache:
          key: v2-front-build-{{ checksum "front/yarn.lock" }}
          paths:
            - ./front/dist

  build_back:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-back-dependencies-{{ checksum "back/yarn.lock" }}
      - run: yarn build:back

  deploy_branch:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy branch to Heroku branch
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/recontact-branch.git $CIRCLE_BRANCH:master --force

  validate_html5v:
    <<: *common_properties
    steps:
      - run: yarn add html5-validator
      - run: ./node_modules/.bin/html5v https://french-test.recontact.me/
      - run: ./node_modules/.bin/html5v https://english-test.recontact.me/articles/85

  validate_html5v_branch:
    <<: *common_properties
    steps:
      - run: yarn add html5-validator
      - run: ./node_modules/.bin/html5v https://recontact-branch.herokuapp.com/
      - run: ./node_modules/.bin/html5v https://recontact-branch.herokuapp.com/articles/85

  lighthouse:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run: yarn lighthouse

  bundlesize:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-build-{{ checksum "front/yarn.lock" }}
      - run: yarn bundlesize

  webpagetest:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run: yarn add webpagetest
      - run: ./node_modules/.bin/webpagetest test https://french-test.recontact.me/ --first --poll --specs tools/webpagetest-threshold.json -k $WEBPAGETEST_API_KEY
      - run: ./node_modules/.bin/webpagetest test https://english-test.recontact.me/articles/85 --first --poll --specs tools/webpagetest-article-threshold.json -k $WEBPAGETEST_API_KEY
      - run: ./node_modules/.bin/webpagetest test https://english-test.recontact.me/articles --first --poll --specs tools/webpagetest-articles-threshold.json -k $WEBPAGETEST_API_KEY

  deploy_staging:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy dev to Heroku staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/recontact-test.git dev:master

  deploy_master:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy master to Recontact (Prod) - Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/recontact.git master

  deploy_cecile:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy master to Cecile - Heroku
          command: |
            git push https://heroku:$HEROKU_CECILE_API_KEY@git.heroku.com/recontact-cecile.git master

  deploy_recontact_api:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy master to Recontact API - Heroku
          command: |
            git push https://heroku:$HEROKU_RECONTACT_API_KEY@git.heroku.com/recontact-api.git master

  deploy_recontact_blog:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy master to Pierre Blog on Heroku
          command: |
            git push https://heroku:$HEROKU_RECONTACT_BLOG_KEY@git.heroku.com/recontact-blog.git master

workflows:
  version: 2
  recontact-workflow:
    jobs:
      - checkout_code
      - install_front:
          requires:
            - checkout_code
      - install_back:
          requires:
            - checkout_code
      - test_front:
          requires:
            - install_front
      - test_back:
          requires:
            - install_back
      - build_front:
          requires:
            - install_front
      - build_back:
          requires:
            - install_back
      - deploy_branch:
          requires:
            - test_front
            - test_back
            - build_front
            - build_back
          filters:
            branches:
              ignore:
                - dev
                - master
      - validate_html5v_branch:
          requires:
            - deploy_branch
      - validate_html5v:
          requires:
            - deploy_staging
      - lighthouse:
          requires:
            - deploy_staging
      - webpagetest:
          requires:
            - deploy_staging
      - bundlesize:
          requires:
            - deploy_staging
      - deploy_staging:
          requires:
            - test_front
            - test_back
            - build_front
            - build_back
          filters:
            branches:
              only: dev
      - deploy_master:
          requires:
            - test_front
            - test_back
            - build_front
            - build_back
          filters:
            branches:
              only: master
      - deploy_recontact_api:
          requires:
            - deploy_master
      - deploy_cecile:
          requires:
            - deploy_master
      - deploy_recontact_blog:
          requires:
            - deploy_master
