[build]
  command = "NITRO_PRESET=netlify npx nuxi build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22.22.0"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  targetPort = 3334
  port = 3333
