[build]
  command = "npx nuxi build && mkdir -p .nuxt/dist/client/_nuxt/builds && cp -r .nuxt/builds/* .nuxt/dist/client/_nuxt/builds/"
  publish = ".nuxt/dist/client"

[build.environment]
  NODE_VERSION = "22.22.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  targetPort = 3334
  port = 3333
