import connectHistoryApiFallback from 'connect-history-api-fallback'

const history = connectHistoryApiFallback({
  // Empty SPA shell generated by nitro: without it, any unknown route returned the homepage HTML
  index: '/200.html',
  rewrites: [
    {
      from: /^\/articles\/static.*$/,
      to(context) {
        const staticPathWithHistory = context.parsedUrl.pathname.replace('/articles', '')
        return `/${staticPathWithHistory}`
      },
    },
  ],
})

module.exports = history
